// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_vscode_version.test.ts.

/** The version of the `@ggdna/dna-vscode` package. */
export const dnaVscodeVersion = '0.2.1';
